server:
  port: 8080
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/kafka-example
  kafka:
    bootstrap-servers: localhost:9092
    listener:
      missing-topics-fatal: false
    consumer:
      group-id: kafka-example
      bootstrapServers: ${spring.kafka.bootstrap-servers}
      enableAutoCommit: true
    producer:
      bootstrap-servers: ${spring.kafka.bootstrap-servers}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    topics:
      kafkaExampleBroadcast: teste.kafka.example.input